"""addCountry

Revision ID: 6ee758d44541
Revises: b92cb7aad6a8
Create Date: 2024-03-03 23:13:03.388594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ee758d44541'
down_revision: Union[str, None] = 'b92cb7aad6a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('icon_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('name')
    )
    op.add_column('users', sa.Column('country_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'users', 'countries', ['country_id'], ['uid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'country_id')
    op.drop_table('countries')
    # ### end Alembic commands ###
