"""add author to collect

Revision ID: d8b4a1721529
Revises: 1a8b89d6d82f
Create Date: 2024-03-11 03:24:59.691644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8b4a1721529'
down_revision: Union[str, None] = '1a8b89d6d82f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collects', sa.Column('author_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'collects', 'users', ['author_id'], ['uid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'collects', type_='foreignkey')
    op.drop_column('collects', 'author_id')
    # ### end Alembic commands ###
